# merge 1 version

version: "2.2"

services:
    ubuntu-base:
        image: ubuntu-base
        build: ubuntu-base
        container_name: ubuntu-base
        hostname: ubuntu-base
    
    ubuntu-java:
        image: ubuntu-java
        build: ubuntu-java
        container_name: ubuntu-java
        hostname: ubuntu-java
        depends_on: ['ubuntu-base']
        
    ubuntu-mysql:
        container_name: ubuntu-mysql
        hostname: ubuntu-mysql
        build: ubuntu-mysql
        image: ubuntu-mysql  
        ports: ["7306:3306"]    
        expose:
            - "7306"     
        environment:
                - MYSQL_PASSWORD=Bea007Bea007
        depends_on: ['ubuntu-java']        
    
    ubuntu-elasticsearch:
        container_name: ubuntu-elasticsearch
        hostname: ubuntu-elasticsearch
        build: ubuntu-elasticsearch
        image: ubuntu-elasticsearch 
        ports: ["7200:9200", "7300:9300"]    
        expose:
            - "7200"    
            - "7300"
        depends_on: ['ubuntu-java']   
    
    # 
    # tool for checking out a condition of elastic search in version of 2.xx
    # kibana:
    #     container_name: kibana
    #     hostname: kibana
    #     build: kibana
    #     image: kibana 
    #     environment:
    #             - ELASTICSEARCH_URL=http://ubuntu-elasticsearch:9200
    #     ports: ["7601:5601"]    
    #     expose:
    #         - "7601"
    #     depends_on: ['ubuntu-elasticsearch']     

    ubuntu-liferay:
        container_name: ubuntu-liferay
        hostname: ubuntu-liferay
        build: ubuntu-liferay
        image: ubuntu-liferay  
        ports: ["7080:8080", "11311:11311", "7001:8000"]    
        expose: 
            - "7080"   
            - "11311"   
            - "7001" 
        # volumes:
        #     - $DOCKER_LIFERAY_HOME:/opt/liferay   
        depends_on: ['ubuntu-mysql', 'ubuntu-elasticsearch'] 
    
