version: "2"

services:
    ubuntu-mysql:
        container_name: ubuntu-mysql
        hostname: ubuntu-mysql
        build: ubuntu-mysql
        image: ubuntu-mysql  
        ports: ["7306:3306"]    
        expose:
            - "7306"     
        environment:
                - MYSQL_PASSWORD=Bea007Bea007
    
    ubuntu-elasticsearch:
        container_name: ubuntu-elasticsearch
        hostname: ubuntu-elasticsearch
        build: ubuntu-elasticsearch
        image: ubuntu-elasticsearch 
        ports: ["7200:9200", "7300:9300"]    
        expose:
            - "7200"    
            - "7300"

    kibana:
        image: docker.elastic.co/kibana/kibana:6.2.4
        container_name: kibana
        ports: ["7601:5601"]
        environment:
            ELASTICSEARCH_URL: http://ubuntu-elasticsearch
        expose:
            - "7601"  
        networks: ['stack']
        depends_on: ['ubuntu-elasticsearch']

    ubuntu-liferay:
        container_name: ubuntu-liferay
        hostname: ubuntu-liferay
        build: ubuntu-liferay
        image: ubuntu-liferay  
        ports: ["7080:8080"]    
        expose:
            - "7080"   
        depends_on: ['ubuntu-mysql', 'ubuntu-elasticsearch'] 

networks: {stack: {}}   
